version: '2'
services:
  image-test:
    build:
      context: .
      args:
        SCRIPT_URL: "https://raw.githubusercontent.com/alexrochas/pranks/master/zsh/cd.sh"
    stdin_open: true
    tty: true
